
services:

  scraper:
    build: ./scraper
    depends_on:
      - kafka
      - mongodb
    env_file:
      - .env
    volumes:
      - ./scraper:/app

  ollama:
    build: ./ollama
    depends_on:
      - kafka
      - mongodb
    env_file:
      - .env
    volumes:
      - ./ollama:/app

  mailer:
    build: ./mailer
    depends_on:
      - kafka
      - mongodb
    env_file:
      - .env
    volumes:
      - ./mailer:/app
