
services:

  scraper:
    build: ./scraper
    depends_on:
      - kafka
      - mongodb
    env_file:
      - .env
    volumes:
      - ./scraper:/app

  llm_client:
    build: ./llm_client
    depends_on:
      - kafka
      - mongodb
    env_file:
      - .env
    volumes:
      - ./llm_client:/app

  mailer:
    build: ./mailer
    depends_on:
      - kafka
      - mongodb
    env_file:
      - .env
    volumes:
      - ./mailer:/app
